config/routes.rb
Rails.application.routes.draw do

  resources :pins
  devise_for :users
  root 'pins#index'

  get 'home/about'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
   has_many :pins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])   
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").page(params[:page]).per(10)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin." if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_alert.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>  
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_index.html.erb
<div class="jumbotron">
  <div class="container jumbo text-center">
   <h1>Welcome to Pin It</h1>

    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark" %>
      <%= link_to "List Pins", pins_path, class: "btn btn-outline-info" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-light" %>
      <%= link_to "Join", new_user_registration_path, class: "btn btn-primary" %>  
    <% end %>

  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
 
    <div class="navbar-brand">
      <%= link_to "Pin It", root_path, class: "pin" %></li>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">

          <%= link_to "Home", root_path, class: "link" %>
          <%= link_to "About Me", home_about_path, class: "link" %>

          <% if user_signed_in? %>
            <%= link_to "Add Pin", new_pin_path, class: "link" %>
            <%= link_to "List Pins", pins_path, class: "link" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "link" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "link" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "link" %>
            <%= link_to "Join", new_user_registration_path, class: "link" %>  
          <% end %>      
      
        </li>
      </ul>
    </div>
  
</nav>

app/views/home/about.html.erb
<h1>About Me</h1>

app/views/home/index.html.erb
<div class="jumbotron  jumbotron-fluid">
  <div class="container jumbo">
   <h1>Welcome to Pin App</h1>

    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark" %>
      <%= link_to "List Pins", pins_path, class: "btn btn-outline-info" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-light" %>
      <%= link_to "Join", new_user_registration_path, class: "btn btn-primary" %>  
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PintClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'home/navbar' %>

    <div class="container">

    <%= render 'home/alert' %>

      <%= yield %>

    </div>

  </body>
  
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

<div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: "form-control" %>
</div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="card edit pin">

  <div class="card-header">
    <h1>Editing Pin</h1>
  </div>

  <div class="card-body edit">

  <%= render 'form', pin: @pin %>

   </div>
  
  <div class="card-footer text-muted">
    <%= link_to 'Show', @pin, class: "btn btn-outline-primary btn-sm" %> 
    <%= link_to 'Back', pins_path, class: "btn btn-outline-primary btn-sm" %> 
  </div>

</div>

app/views/pins/index.html.erb
<%= render 'home/index' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">

  <% @pins.each do |pin| %>

    <div class="box">
      <div class="card">  
          <%= link_to image_tag(pin.image.url(:medium)), pin %>
        <div class="card-body">
           <%= pin.description %><br/>
           <%= pin.user.name if pin.user %>
          <p>
           <% if pin.user == current_user %>
             <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-primary btn-sm" %>
             <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
           <% end %>
          </p>
        </div>
      </div>   
    </div>

  <% end %>

</div>

<%= paginate @pins %>

app/views/pins/new.html.erb
<div class="card new pin">

  <div class="card-header">
     <h1>New Pin</h1>
  </div>

  <div class="card-body add">

    <%= render 'form', pin: @pin %>
     
  </div>
  
  <div class="card-footer">
     <%= link_to 'Back', pins_path, class: "btn btn-outline-primary btn-sm" %>
  </div>
</div>




  
 

app/views/pins/show.html.erb
<div class="card show" style="width: 18rem;">

   <%= image_tag @pin.image.url(:medium) %>

  <div class="card-body show">
     
    <%= @pin.description %><br/>
    <%= @pin.user.name %>

    <p>
      <% if @pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(@pin), class: "btn btn-primary btn-sm" %><br/> 
      <% end %>

      <%= link_to 'Back', pins_path %>
    </p>

  </div>
  
</div>
    
  